import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Youtube,Languages,Download,Play,Sparkles,Clock3,CheckCircle2,Loader2,AlertCircle} from "lucide-react";
import "./styles.css";
const languages=["Gujarati","Hindi","Marathi","English","Bengali","Tamil","Telugu","Kannada","Malayalam","Punjabi"];
const API=import.meta.env.VITE_API_URL||"";
function App(){
 const [url,setUrl]=useState("");const [language,setLanguage]=useState("Gujarati");const [status,setStatus]=useState("idle");const [job,setJob]=useState(null);const [error,setError]=useState("");
 useEffect(()=>{if(!job?.jobId)return;const timer=setInterval(async()=>{try{const r=await fetch(`${API}/api/dub/${job.jobId}`);const d=await r.json();setJob(d);setStatus(d.status);if(d.status==="ready"||d.status==="error")clearInterval(timer)}catch(e){setError(e.message)}},1200);return()=>clearInterval(timer)},[job?.jobId]);
 const start=async()=>{if(!url.trim())return;setError("");setJob(null);setStatus("queued");try{const r=await fetch(`${API}/api/dub`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,targetLanguage:language})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not start job");setJob(d)}catch(e){setStatus("error");setError(e.message)}};
 const ready=status==="ready";const busy=["queued","downloading","extracting audio","transcribing","translating","generating voice","rendering video"].includes(status);
 return <div className="app"><header><div className="brand"><span className="logo"><Youtube size={23}/></span><div><b>LinguaDub</b><small>YouTube Language Changer</small></div></div><span className="pill"><Sparkles size={15}/> AI Dubbing</span></header><main><section className="hero"><div className="eyebrow">FAST AI VIDEO TRANSLATION</div><h1>Watch any video<br/><span>in your language.</span></h1><p>Paste a YouTube link, choose a language, and create a dubbed version with translated speech while keeping the original visuals.</p></section><section className="card"><label><Youtube size={18}/> YouTube video URL</label><div className="urlrow"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/><button className="paste" onClick={async()=>{try{setUrl(await navigator.clipboard.readText())}catch{}}}>Paste</button></div><label><Languages size={18}/> Translate to</label><div className="selectrow"><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select><button className="primary" onClick={start} disabled={!url||busy}>{busy?<><Loader2 className="spin" size={18}/> Processing...</>:<><Sparkles size={18}/> Translate & Dub</>}</button></div><div className="speed"><Clock3 size={17}/><div><b>Fast processing</b><span>Short videos can often finish in under a minute; longer videos take longer.</span></div></div>{error&&<div className="error"><AlertCircle size={17}/>{error}</div>}</section><section className="player card"><div className="playerhead"><div><b>Translated video</b><span>{ready?`Ready in ${language}`:busy?`Creating ${language} dub…`:"Your result will appear here"}</span></div>{ready&&<a className="download" href={`${API}${job.videoUrl}`} download><Download size={17}/> Download MP4</a>}</div><div className="screen">{status==="idle"&&<div className="empty"><Play size={42}/><b>Paste a video link to begin</b><span>The original visuals stay unchanged while the spoken language is dubbed.</span></div>}{busy&&<div className="empty"><Loader2 className="spin" size={42}/><b>{status}</b><span>Download → extract audio → transcribe → translate → generate voice → render</span><div className="progress"><i style={{width:`${job?.progress||5}%`}}/></div></div>}{status==="error"&&<div className="empty"><AlertCircle size={42}/><b>Processing failed</b><span>{job?.error||error||"Please try again."}</span></div>}{ready&&<div className="readyvideo"><video controls src={`${API}${job.videoUrl}`}/><div className="readybadge"><CheckCircle2 size={18}/> Translation ready</div></div>}</div></section><div className="steps"><div><span>01</span><b>Paste link</b><small>Add a public YouTube URL</small></div><div><span>02</span><b>Choose language</b><small>Select your target language</small></div><div><span>03</span><b>Dub & download</b><small>Generate and save the MP4</small></div></div></main><footer>LinguaDub • AI-powered translation interface</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
