import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Youtube,Languages,Download,Play,Sparkles,Clock3,CheckCircle2,Loader2,AlertCircle,Link2,ChevronDown,Share2,RotateCcw,ShieldCheck} from "lucide-react";
import "./styles.css";
const languages=["Gujarati","Hindi","Marathi","English","Bengali","Tamil","Telugu","Kannada","Malayalam","Punjabi"];
const labels={queued:"Queued",downloading:"Downloading video","extracting audio":"Extracting audio",transcribing:"Transcribing speech",translating:"Translating","generating voice":"Generating voice","rendering video":"Rendering video"};
const API=import.meta.env.VITE_API_URL||"";
function App(){
 const [url,setUrl]=useState(""); const [language,setLanguage]=useState("Gujarati"); const [status,setStatus]=useState("idle"); const [job,setJob]=useState(null); const [error,setError]=useState(""); const [tab,setTab]=useState("home");
 useEffect(()=>{if(!job?.jobId)return;let stopped=false;let timer;const poll=async()=>{try{const r=await fetch(`${API}/api/dub/${job.jobId}`,{cache:"no-store"});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Status check failed (${r.status})`);if(stopped)return;setJob(d);setStatus(d.status);if(d.status==="error"){setError(d.error||"Dubbing failed");clearInterval(timer)}if(d.status==="ready")clearInterval(timer)}catch(e){if(stopped)return;setStatus("error");setError(e.message||"Could not check dubbing status");clearInterval(timer)}};timer=setInterval(poll,1200);poll();return()=>{stopped=true;clearInterval(timer)}},[job?.jobId]);
 const validUrl=/^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.be)\//i.test(url.trim());
 const normalizeUrl=value=>{const v=value.trim();return /^https?:\/\//i.test(v)?v:`https://${v}`};
 const start=async()=>{if(!validUrl)return setError("Please enter a valid YouTube link.");const normalized=normalizeUrl(url);setUrl(normalized);setError("");setJob(null);setStatus("queued");try{const r=await fetch(`${API}/api/dub`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:normalized,targetLanguage:language})});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Could not start dubbing (${r.status})`);setJob(d)}catch(e){setStatus("error");setError(e.message||"Could not start dubbing")}};
 const share=async()=>{if(!job?.videoUrl)return;const link=`${API}${job.videoUrl}`;try{if(navigator.share)await navigator.share({title:`LinguaDub — ${language} dub`,url:link});else await navigator.clipboard.writeText(link)}catch{}};
 const ready=status==="ready";const busy=["queued","downloading","extracting audio","transcribing","translating","generating voice","rendering video"].includes(status);
 return <div className="app"><header className="topbar"><div className="brand"><span className="logo"><Youtube size={21}/></span><div><b>LinguaDub</b><small>AI Video Dubbing</small></div></div><button className="iconbtn" aria-label="AI dubbing"><Sparkles size={18}/></button></header><main>
 {tab==="home"&&<><section className="hero"><div className="eyebrow">AI POWERED</div><h1>Videos in <span>your language.</span></h1><p>Translate spoken audio while keeping the original video unchanged.</p></section>
 <section className="composer"><div className="sectiontitle"><span className="roundicon"><Link2 size={18}/></span><div><b>Video link</b><small>Paste a YouTube URL</small></div></div><div className="urlbox"><input value={url} onChange={e=>{setUrl(e.target.value);setError("")}} placeholder="youtube.com/watch?v=..." inputMode="url"/><button className="paste" onClick={async()=>{try{const v=await navigator.clipboard.readText();setUrl(v);setError("")}catch{}}}>Paste</button></div><div className="sectiontitle language-title"><span className="roundicon"><Languages size={18}/></span><div><b>Target language</b><small>Choose the language for the new voice</small></div></div><div className="languagebox"><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={18}/></div>{error&&<div className="error"><AlertCircle size={17}/>{error}</div>}<button className="primary" onClick={start} disabled={!url.trim()||busy}>{busy?<><Loader2 className="spin" size={19}/> Creating dub...</>:<><Sparkles size={19}/> Translate & Dub</>}</button><div className="trust"><ShieldCheck size={16}/><span>Use only videos you own or are authorized to process.</span></div></section>
 <section className="resultcard"><div className="resulthead"><div><b>Translated video</b><small>{ready?`Ready • ${language}`:busy?`${labels[status]||"Processing"} • ${language}`:"Your finished video appears here"}</small></div>{ready&&<div className="resultactions"><button className="smallbtn" onClick={share} aria-label="Share video"><Share2 size={16}/></button><a className="download" href={`${API}${job.videoUrl}`} download><Download size={16}/><span>MP4</span></a></div>}</div><div className="screen">{status==="idle"&&<div className="empty"><span className="bigplay"><Play size={30}/></span><b>Ready to translate</b><span>Paste a YouTube link above to get started.</span></div>}{busy&&<div className="empty"><Loader2 className="spin" size={38}/><b>{labels[status]||"Processing"}</b><span>Downloading • translating • generating voice</span><div className="progress"><i style={{width:`${job?.progress||8}%`}}/></div></div>}{status==="error"&&<div className="empty"><AlertCircle size={38}/><b>Something went wrong</b><span>{job?.error||error||"Please check the link and try again."}</span><button className="retry" onClick={start}><RotateCcw size={16}/> Try again</button></div>}{ready&&<div className="readyvideo"><video controls playsInline src={`${API}${job.videoUrl}`}/><div className="readybadge"><CheckCircle2 size={17}/> Translation ready</div></div>}</div></section>
 <section className="steps"><div><span>01</span><b>Paste link</b><small>Add your YouTube video</small></div><div><span>02</span><b>Choose language</b><small>Select your target voice</small></div><div><span>03</span><b>Download</b><small>Save the dubbed MP4</small></div></section></>}
 {tab==="history"&&<section className="placeholder"><Clock3 size={34}/><h2>Recent dubbing</h2><p>Completed videos will appear here in a future update.</p></section>}
 {tab==="settings"&&<section className="placeholder"><Sparkles size={34}/><h2>LinguaDub Settings</h2><p>Default language: <b>{language}</b></p><p>Backend: {API?"Connected API":"Same-origin API"}</p></section>}
 </main><nav className="bottomnav"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Sparkles size={20}/><span>Dub</span></button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}><Clock3 size={20}/><span>History</span></button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Languages size={20}/><span>Settings</span></button></nav><footer>LinguaDub • AI-powered translation</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
